application: sellweek-testing
version: 0-0
runtime: go
api_version: go1

handlers:
- url: /admin
  static_dir: admin
  login: admin
  auth_fail_action: redirect
- url: /broadcast
  static_dir: broadcast
- url: /.*
  script: _go_app